### ISSUE TITLE
Erro ortográfico

### ISSUE THREAD

**Issue by mepossamai** [gomex/deploy-em-producao#19]
Em Definindo Testes (https://github.com/gomex/deploy-em-producao/blob/main/manuscript/definindo_testes.md) há um erro ortográfico na palavra "verficiações" - na frase:

"A gente volta nesse assunto quando formos falar de Testes Contínuos e onde encaixar cada uma das verficiações que falamos aqui. :)"

**Comment by kelvins** [comment]
Olá @mepossamai, acredito que esse typo já foi corrigido no PR https://github.com/gomex/deploy-em-producao/pull/17.
